// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $acerca_de from "./routes/acerca-de.tsx";
import * as $contactar from "./routes/contactar.tsx";
import * as $index from "./routes/index.tsx";
import * as $productos from "./routes/productos.tsx";
import * as $servicios from "./routes/servicios.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/acerca-de.tsx": $acerca_de,
    "./routes/contactar.tsx": $contactar,
    "./routes/index.tsx": $index,
    "./routes/productos.tsx": $productos,
    "./routes/servicios.tsx": $servicios,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
